### PR TITLE
multiarch support

### PR DESCRIPTION
**Pull request by lucor**
This PR adds support to multi architectures and moves to [Zig](ziglang.org) as toolchain for cross compiling.
The objective is to support the `amd64` and `arm64` as host architecture and the os/arch supported by fyne-cross  v1.3.0.

To test the images the fyne-cross version from https://github.com/fyne-io/fyne-cross/pull/148 can be used.

## Notable changes
- Move to Zig as toolchain for cross compiling
- Update the OS for the base image to debian bullseye. Note:Zig defaults to glibc 2.19 for cross compiling, this should ensure backward compatibility with old linux distribution. Fixes: https://github.com/fyne-io/fyne-cross/issues/88
- Add support to host multi architectures: `amd64` and `arm64`
- Add support to Windows arm64 target. Fixes: https://github.com/fyne-io/fyne-cross/issues/84

## Supported targets

Table below reports the status of `fyne-cross`'s supported cross compilation targets.
The supported architectures for the host are `amd64`and `arm64`. 
|                | amd64              | arm64 |
| -------------- | ------------------ | ----- |
| android/386    | :white_check_mark: | N/A |
| android/amd64   | :white_check_mark: | N/A |
| android/arm    | :white_check_mark: | N/A |
| android/arm64  | :white_check_mark: | N/A |
| darwin/amd64   | :white_check_mark: | :white_check_mark: |
| darwin/arm64   | :white_check_mark: | :white_check_mark: |
| freebsd/amd64  | :white_check_mark: | :white_check_mark: |
| freebsd/arm64  | :white_check_mark: | :white_check_mark: |
| linux/amd64    | :white_check_mark: | :white_check_mark: |
| linux/386      | :white_check_mark: | :white_check_mark: |
| linux/arm      | :white_check_mark: | :white_check_mark: |
| linux/arm64    | :white_check_mark: | :white_check_mark: |
| windows/amd64  | :white_check_mark: | :white_check_mark: |
| windows/arm64    | :white_check_mark: | :white_check_mark: |
| windows/386    | :white_check_mark: | :white_check_mark: |
| web                  | :white_check_mark: | :white_check_mark: |

> Note: 
> - darwin images should work out of the box against MacOSX SDKs 11.3. 
> Other SDK versions could require a different min SDK version that can specified using the `--macosx-version-min` flag  
> - android NDK is not available for linux/arm64, cross-compilation from arm64 hosts won't be supported in this initial release

### CODE REVIEW

**Comment by Jacalz** [comment]
Well done. Looking forward to seeing this completed :)

**Comment by Bluebugs** [comment]
This is pretty cool. I have setup the fyne Mac M1 to build this branch and test it. The trees are in:
- /Users/fyne/go/src/github.com/fyne-io/fyne-cross-images
- /Users/fyne/go/src/github.com/fyne-io/fyne-cross

They both point to your branches at the moment (the prompt would point that out). I can report that the Linux image are actually working on ARM64 and can target other arch :-) I had to modify a bit the layout as you can see as I tried to use docker buildx command and it can only pick Dockerfile in a specific repository.

This is pretty exciting! Great work!

**Comment by lucor** [comment]
Great and thanks for testing!
I'll modify the layout to have one Dockerfile per folder.

**Comment by Bluebugs** [comment]
This is looking pretty good! How do you want to proceed with the multi image? Do you want to do that in a separate PR or add a few lines for handling buildx/buildah? I have tried buildah and the images on Linux for Linux/Windows on ARM64 and AMD64. I still need to try the darwin image. I would not expect the Android one to work, but I might be wrong. Should I test Android image running on ARM64?

**Comment by lucor** [comment]
> Should I test Android image running on ARM64?

As discussed in chat the android NDK is not available for linux/arm64, cross-compilation from arm64 hosts won't be supported in this initial release.

**Review by Bluebugs — APPROVED** [review]
Tested on ARM64 and AMD64, along with multi arch. This work nicely!

**Pull request merged**
