### PR TITLE
Update Go to 1.21.8 and Fyne to v2.4.4

### PR DESCRIPTION
**Pull request by Jacalz**
Update to latest stable versions for Go 1.21.x and Fyne v2.4.x. Not updating to Go 1.22.1 because it only contained security patches over 1.22.0 and i don't deem that ready for mass deployment yet.

### CODE REVIEW

**Review by Bluebugs — APPROVED** [review]
Looks good. Would be great to work on automation of generating this kind of pr to not fall behind.

**Comment by Jacalz** [comment]
The CI pipeline is getting this error. I don't really know why.
```
2024-03-18T20:03:16.5815121Z go build github.com/go-gl/gl/v3.2-core/gl:
2024-03-18T20:03:16.5815804Z # pkg-config --cflags  -- gl gl
2024-03-18T20:03:16.5816601Z Package gl was not found in the pkg-config search path.
2024-03-18T20:03:16.5817491Z Perhaps you should add the directory containing `gl.pc'
2024-03-18T20:03:16.5818238Z to the PKG_CONFIG_PATH environment variable
2024-03-18T20:03:16.5818844Z No package 'gl' found
2024-03-18T20:03:16.5819442Z Package gl was not found in the pkg-config search path.
2024-03-18T20:03:16.5819962Z Perhaps you should add the directory containing `gl.pc'
2024-03-18T20:03:16.5820679Z to the PKG_CONFIG_PATH environment variable
2024-03-18T20:03:16.5821281Z No package 'gl' found
2024-03-18T20:03:16.5821857Z pkg-config: exit status 1
2024-03-18T20:03:16.5822893Z go build github.com/go-gl/glfw/v3.3/glfw:
2024-03-18T20:03:16.5823514Z # pkg-config --cflags  -- x11 xau xcb xdmcp
2024-03-18T20:03:16.5824242Z Package x11 was not found in the pkg-config search path.
2024-03-18T20:03:16.5825173Z Perhaps you should add the directory containing `x11.pc'
2024-03-18T20:03:16.5826263Z to the PKG_CONFIG_PATH environment variable
2024-03-18T20:03:16.5826791Z No package 'x11' found
2024-03-18T20:03:16.5827380Z Package xau was not found in the pkg-config search path.
2024-03-18T20:03:16.5828276Z Perhaps you should add the directory containing `xau.pc'
2024-03-18T20:03:16.5829064Z to the PKG_CONFIG_PATH environment variable
2024-03-18T20:03:16.5829712Z No package 'xau' found
2024-03-18T20:03:16.5830471Z Package xcb was not found in the pkg-config search path.
2024-03-18T20:03:16.5831358Z Perhaps you should add the directory containing `xcb.pc'
2024-03-18T20:03:16.5832150Z to the PKG_CONFIG_PATH environment variable
2024-03-18T20:03:16.5832838Z No package 'xcb' found
2024-03-18T20:03:16.5833435Z Package xdmcp was not found in the pkg-config search path.
2024-03-18T20:03:16.5834242Z Perhaps you should add the directory containing `xdmcp.pc'
2024-03-18T20:03:16.5834812Z to the PKG_CONFIG_PATH environment variable
2024-03-18T20:03:16.5835224Z No package 'xdmcp' found
2024-03-18T20:03:16.5835639Z pkg-config: exit status 1
2024-03-18T20:03:16.5835835Z 
2024-03-18T20:03:16.5836172Z error building application: exit status 1
2024-03-18T20:03:18.0855586Z [✗] could not package the Fyne app: could not package the Fyne app: exit status 1
2024-03-18T20:03:18.0877084Z ##[error]Process completed with exit code 1.
2024-03-18T20:03:18.0955093Z Post job cleanup.
2024-03-18T20:03:18.1779004Z [command]/usr/bin/git version
2024-03-18T20:03:18.1824034Z git version 2.43.2
2024-03-18T20:03:18.1863964Z Temporarily overriding HOME='/home/runner/work/_temp/8e225df6-e1af-41dd-b8e8-ca3385ca62d3' before making global git config changes
2024-03-18T20:03:18.1865864Z Adding repository directory to the temporary git global config as a safe directory
2024-03-18T20:03:18.1871053Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/fyne-cross-images/fyne-cross-images/calculator
2024-03-18T20:03:18.1911734Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-03-18T20:03:18.1949865Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-03-18T20:03:18.2192892Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-03-18T20:03:18.2221077Z http.https://github.com/.extraheader
2024-03-18T20:03:18.2232028Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2024-03-18T20:03:18.2267892Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-03-18T20:03:18.2611727Z Post job cleanup.
2024-03-18T20:03:18.3433279Z [command]/usr/bin/git version
2024-03-18T20:03:18.3476705Z git version 2.43.2
2024-03-18T20:03:18.3514540Z Temporarily overriding HOME='/home/runner/work/_temp/257c1714-3543-4ec6-b75c-e10d58497853' before making global git config changes
2024-03-18T20:03:18.3516012Z Adding repository directory to the temporary git global config as a safe directory
2024-03-18T20:03:18.3520432Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/fyne-cross-images/fyne-cross-images/fyne-cross
2024-03-18T20:03:18.3560070Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-03-18T20:03:18.3597691Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-03-18T20:03:18.3835561Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-03-18T20:03:18.3863149Z http.https://github.com/.extraheader
2024-03-18T20:03:18.3873822Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2024-03-18T20:03:18.3910253Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-03-18T20:03:18.4262662Z Post job cleanup.
2024-03-18T20:03:18.5080322Z [command]/usr/bin/git version
2024-03-18T20:03:18.5124251Z git version 2.43.2
2024-03-18T20:03:18.5162464Z Temporarily overriding HOME='/home/runner/work/_temp/09f643d9-5974-45a9-81a7-2aaa7856b29b' before making global git config changes
2024-03-18T20:03:18.5163627Z Adding repository directory to the temporary git global config as a safe directory
2024-03-18T20:03:18.5168854Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/fyne-cross-images/fyne-cross-images/fyne-cross-images
2024-03-18T20:03:18.5208000Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-03-18T20:03:18.5244703Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-03-18T20:03:18.5479901Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-03-18T20:03:18.5506878Z http.https://github.com/.extraheader
2024-03-18T20:03:18.5517802Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2024-03-18T20:03:18.5553951Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-03-18T20:03:18.6012855Z Cleaning up orphan processes

```

**Comment by Bluebugs** [comment]
It seems the freebsd image may have stored the pkgconfig file that glfw needs in a different place and they are not getting picked. This would require looking into the image to figure out what is going on.

**Review by andydotxyz — APPROVED** [review]

**Comment by Jacalz** [comment]
I think I managed to get FreeBSD builds to work by making sure that the we use latest minor release of the oldest supported FreeBSD version. This means upgrading from FreeBSD 12.4 as the oldest supported version to 13.4 but I think it is fine as 12.4 no longer get updates (and there is no removal of hardware support inline macOS).

I don’t have access to my development machine and won’t have until over a week forward. I’d appreciate if someone could test this locally.

**Comment by Bluebugs** [comment]
> I don’t have access to my development machine and won’t have until over a week forward. I’d appreciate if someone could test this locally.

I don't have freebsd locally, so I can't really tests the result. Do you know of anyone that does?

Something for next call, discuss github runner for arm, android and freebsd so we can tests those builds.

**Comment by Jacalz** [comment]
> I don't have freebsd locally, so I can't really tests the result. Do you know of anyone that does?

I usually just spin up a VM with GhostBSD. It's not that hard and cumbersome.

**Review by andydotxyz — APPROVED** [review]

**Comment by Jacalz** [comment]
I think it might be time to consider doing a new release of the images now that this is merged (after some more testing of course).

**Comment by Bluebugs** [comment]
> I think it might be time to consider doing a new release of the images now that this is merged (after some more testing of course).

This is the easiest things to do with this repo. Just push a new tag on top of master, rest is automated. I am very close to think that any commit to master that pass CI should automatically trigger a new tag which would trigger the CD. There is no value for large release.

**Comment by Jacalz** [comment]
Do you mean that we don't need to do a release because fyne-cross downloads tags directly off of the main branch?

**Comment by Bluebugs** [comment]
> Do you mean that we don't need to do a release because fyne-cross downloads tags directly off of the main branch?

I just mean that if you want to do a release, just push a new tag and it will push the images to docker. You can also add release notes to the github repository, but the tag is the useful bit here.

**Pull request merged**
